/**
 * Application error codes.
 * Each code maps to a specific error scenario.
 */
export const ErrorCodes = {
  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  BAD_REQUEST: 'BAD_REQUEST',
  RATE_LIMITED: 'RATE_LIMITED',
  TIMEOUT: 'TIMEOUT',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_INVALID: 'MFA_INVALID',
  PASSWORD_EXPIRED: 'PASSWORD_EXPIRED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  // Business
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
  INVALID_STATE: 'INVALID_STATE',
  OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
  DEPENDENCY_EXISTS: 'DEPENDENCY_EXISTS',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',

  // Integration
  INTEGRATION_ERROR: 'INTEGRATION_ERROR',
  WEBHOOK_FAILED: 'WEBHOOK_FAILED',
  THIRD_PARTY_TIMEOUT: 'THIRD_PARTY_TIMEOUT',

  // Audit
  AUDIT_LOG_FAILED: 'AUDIT_LOG_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
